### ISSUE TITLE
Versioning_Toolkit

### ISSUE THREAD

**Issue by kThorsager** [BHoM/Versioning_Toolkit#19]
@adecler What is the correct syntax for deprecating a method so that the Versioning_Toolkit picks it up?

I have tried looking at existing deprecated methods, but they are not consistent and I seem unable to make it work. 

Or am I simply miss-remembering that deprecated components in the grasshopper canvas would get updated?

This is more specifically related to the planed migration of methods from the Common_Engine to the Spatial_Engine if that makes any difference. 
https://github.com/BHoM/BHoM_Engine/issues/1470

**Comment by adecler** [comment]
@kThorsager , sorry, this still needs to be documented properly. It also needs to have the chain of upgraders enable since we are not in 3.0 anymore. 

The way to get a deprecated method to be updated automatically is to add it to the `Converter.ToNewMethod` dictionary you can find here: https://github.com/BHoM/Versioning_Toolkit/blob/master/BHoMUpgrader30/MethodConverter.cs
